name: Mobile Games
favicon: null
layout_spectrum: 0.37759
typography_spectrum: 0.6095831035636365
title: F2P Mobile Games
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
